name: studybloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  auto_route: ^7.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  json_annotation: ^4.8.1
# dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf``
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
